openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /studentapi/:
    get:
      operationId: listStudents
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
          description: ''
      tags:
      - studentapi
    post:
      operationId: createStudent
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Student'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
      tags:
      - studentapi
  /studentapi/{id}/:
    get:
      operationId: retrieveStudent
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this student.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
      tags:
      - studentapi
    put:
      operationId: updateStudent
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this student.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Student'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
      tags:
      - studentapi
    patch:
      operationId: partialUpdateStudent
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this student.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Student'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
          description: ''
      tags:
      - studentapi
    delete:
      operationId: destroyStudent
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this student.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - studentapi
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
        roll:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        city:
          type: string
          maxLength: 50
      required:
      - name
      - roll
      - city
